import type { Metadata } from "next";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { Roboto } from 'next/font/google';
import { ThemeProvider } from '@mui/material/styles';
import theme from '@/theme';
import { Box, CssBaseline, Toolbar } from "@mui/material";
import Grid from '@mui/material/Grid2';
import ResponsiveNav from "@/app/ui/navigation/ResponsiveNav";
import '@fontsource-variable/noto-serif-jp';
import Footer from "@/app/ui/navigation/Footer";

const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const drawerWidth = 240;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={roboto.variable}>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <Box sx={{ display: 'flex' }}>
              <CssBaseline />
              <ResponsiveNav drawerWidth={240} />
              <Grid
                direction="column"
                sx={{
                  flexGrow: 1, width: { sm: `calc(100% - ${drawerWidth}px)` }, minHeight: '100vh',
                  justifyContent: 'flex-start'
                }}
              >
                <Box
                  component="main"
                  sx={{ p: 3 }}
                >
                  <Toolbar />
                  {children}
                </Box>
                <Footer drawerWidth={240} />
              </Grid>
            </Box>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
